### ISSUE TITLE
Bot does not process existing input on startup

### ISSUE THREAD

**Issue by mattmoon1123** [lemonjesus/TranscodeBot#7] opened 2020-05-24 23:45 UTC
Starting/restarting the bot while file exist in the input folder does not result in the bot processing these files until they are `touch`ed again

**Comment by taylorz1** [comment] 2020-05-24 23:50
The bot works on events and would need to be rearchitected to clear the current queue if we actually want this feature. It's likely we would need an additional check on startup to see if the object exists.

Another strategy is that if something fails somehow (or the event is unprocessed) we move it to a DLQ directory.

Technically this is WAI.

**Comment by lemonjesus** [comment] 2020-05-25 21:20
this was by design because there were times I'd restart the JS bot and it would start crunching through the input directory again even though everything was finished and it was super annoying. I'm not sure if I agree with past me's decision to make it this way. maybe I'll make it an env flag since now incomplete transcodes don't destroy the output directory

**Comment by lemonjesus** [comment] 2020-05-26 02:54
fixed in version 2.1

**Closed by lemonjesus** 2020-05-26 02:54 UTC
Labels: enhancement
