### ISSUE TITLE
Something went wrong when it started to work on the video track

### ISSUE THREAD

**Issue by mattmoon1123** [lemonjesus/TranscodeBot#19] opened 2021-01-02 19:10 UTC
```I, [2021-01-02T15:34:33.857906 #1]  INFO -- : working on /input/movies/Autumn Leaves (1956)/Autumn Leaves (1956).mp4 -> /output/movies/Autumn Leaves (1956)/Autumn Leaves (1956).mkv
I, [2021-01-02T15:34:33.858175 #1]  INFO -- : correcting permissions on /tmp/movies/Autumn Leaves (1956)
I, [2021-01-02T15:34:34.054984 #1]  INFO -- : transcoding /input/movies/Autumn Leaves (1956)/Autumn Leaves (1956).mp4
E, [2021-01-02T15:34:34.220207 #1] ERROR -- : Error processing /input/movies/Autumn Leaves (1956)/Autumn Leaves (1956).mp4:
E, [2021-01-02T15:34:34.220309 #1] ERROR -- : ffmpeg version 4.1.4 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-cuda --enable-nvenc --enable-cuvid --enable-libnpp --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-libkvazaar --enable-libaom --extra-libs=-lpthread --enable-postproc --enable-small --enable-version3 --extra-cflags='-I/opt/ffmpeg/include -I/opt/ffmpeg/include/ffnvcodec -I/usr/local/cuda/include/' --extra-ldflags='-L/opt/ffmpeg/lib -L/usr/local/cuda/lib64/ -L/usr/local/cuda/lib32/' --extra-libs=-ldl --prefix=/opt/ffmpeg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/input/movies/Autumn Leaves (1956)/Autumn Leaves (1956).mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2036-02-06T06:28:16.000000Z
    encoder         : HandBrake 0.10.2 2015060900
  Duration: 01:41:51.92, start: 0.000000, bitrate: 1298 kb/s
    Stream #0:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 960x720, 1132 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2036-02-06T06:28:16.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 160 kb/s (default)
    Metadata:
      creation_time   : 2036-02-06T06:28:16.000000Z
      handler_name    : English
    Stream #0:2(eng): Subtitle: mov_text (tx3g / 0x67337874), 960x60, 0 kb/s (default)
    Metadata:
      creation_time   : 2036-02-06T06:28:16.000000Z
      handler_name    : SubtitleHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (libx265))
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
x265 [info]: HEVC encoder version 3.1.1+1-04b37fdfd2dc
x265 [info]: build info [Linux][GCC 7.4.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
x265 [info]: Main profile, Level-3.1 (Main tier)
x265 [info]: Thread pool created using 24 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(12 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 44 / 2 / 2
x265 [info]: Keyframe min / max / scenecut / bias: 25 / 250 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 15 / 4 / 0
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / on / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 1 / 1.0 / 16 / 1
x265 [info]: Rate Control / qCompress            : CRF-22.0 / 0.80
x265 [info]: tools: rd=2 psy-rd=0.70 rdoq=1 psy-rdoq=5.00 rskip signhide tmvp
x265 [info]: tools: fast-intra strong-intra-smoothing lslices=4 deblock sao
[matroska @ 0x55c97777ad40] Subtitle codec 94213 is not supported.
Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
Error initializing output stream 0:0 --

encoded 0 frames
Conversion failed!

E, [2021-01-02T15:34:34.221965 #1] ERROR -- : transcode failed, took 0.16539773 seconds
I, [2021-01-02T15:34:34.222009 #1]  INFO -- : finished with /input/movies/Autumn Leaves (1956)/Autumn Leaves (1956).mp4```

**Comment by mattmoon1123** [comment] 2021-01-02 19:13
Nvm despite complaining about initializing the video track, the subtitles are the problem. I'll rip those out myself and then resubmit, but it would be nice if if the bot could just ignore subtitles it can't handle

**Comment by lemonjesus** [comment] 2021-01-02 19:19
Closing as a duplicate of #16 - but in general one off subtitle issues are a problem with the source file, not the bot. I forget what Subtitle codec 94213 is, but Matroska doesn't support it. The bot instructs `ffmpeg` to pass the subtitles through untouched. We _could_ convert them all to SRT but then I think you'd have an even higher error rate with image-based subtitles. But also idk how common they are.

Either way, the solution is to modify the bot's `ffmpeg` command or do it by hand using a modified `ffmpeg` command. Either way, tell it to convert the subtitles to something else (srt maybe?) or strip them entirely.

**Closed by lemonjesus** 2021-01-02 19:19 UTC
